version: "3.5"

services:
  cardano-node:
    container_name: node-${NETWORK}-container
    network_mode: "host"
    build: ./
    restart: always
    volumes:
      - ./node-${NETWORK}/db:/data/db
      - ./node-${NETWORK}/config:/config
      - ./node-${NETWORK}/ipc:/ipc
      - ./keys:/keys
      - ./txs:/txs
      - ./dumps:/dumps
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  node-ipc:
