name: test start node

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-start-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        shell: bash
        run: |
          timeout 1m /bin/bash ./start-docker.sh
