name: test start node

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-start-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Start node, wait 60s then stop node
        shell: bash
        run: |
          /bin/bash ./start-docker.sh 2>&1 | tee script_output.txt &
          sleep 60
          /bin/bash ./stop-docker.sh